public class CalculatorClass {
    public static void add(){
         Integer a = 10,b = 20;
        Integer sum = a+b;
        System.debug('A+B'+sum);
    }

   public static void sub(){
            Integer a = 30,b = 20;
            Integer sub = a-b;
            System.debug('Sub of a and b'+sub);
    
}

}
       

//===================================================================================================================