public class MapDemo {
    public static void mapMethod()
    {
        Map<integer , string> inttostrngmap = New Map<integer , string>();
        list<String> strlst = new list<string> ();
        inttostrngmap.put(1,'yash');
        inttostrngmap.put(2,'yas');
        inttostrngmap.put(5,'sh');
        set<integer> intset = new set<integer>();
      
///Map<Id , Account> inttostrngmap = New Map<account , string>();
      
        
        // system.debug(''+inttostrngmap.isempty());
        //intset = inttostrngmap.keyset(); that will show key values in set 
        //system.debug(intset); 
     
        
         //   strlst = inttostrng.values(); 
        // system.debug(strlst);      all elements of string will be there by values() method
        //                          if you want key elements than .keyset()
     
        
        //system.debug(inttostrng.size());no. of record in map
       
        //inttostrng.remove(2);           remove(enterkey)Method
        //system.debug(inttostrng); here the value will deleted with the key only
        
        
    }
}