public class soqlrelatedrecords {
    public static void insertupdate()
        
    {//insert parent than
        /*account acc = new account(name= 'sanjay' , phone = '8787');
   
     insert acc;
     
    //insert their related record with help of lookup of child (accountid = acc.id)
     
     contact con = new contact(accountID = acc.id , firstname = 'hariom' , lastname ='om' , phone ='7878');
     insert con;
 
        //update related record , first we do query than
        //add values than update
        
       contact con = [SELECT ID , name , PHONE , ACCOUNT.PHONE ,account.name
                      FROM CONTACT WHERE NAME = 'hariom om'];
        con.phone = '4321';
        con.account.phone = '1234';
        con.account.name = 'rohittttttt';
        update con;
        update con.account;*/
 
     }
}